---

apiVersion: v1
kind: Service
metadata:
  name: upload1
spec:
  selector:
    app: upload1
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload1
  template:
    metadata:
      labels:
        app: upload1
    spec:
      containers:
        - image: svenstaro/miniserve:alpine
          name: miniserve
          args:
            - -u
            - -U
            - /mnt/baza
          volumeMounts:
            - name: emptydir-baza
              mountPath: /mnt/baza
          ports:
            - containerPort: 8080
      volumes:
        - name: emptydir-baza
          emptyDir:


---

apiVersion: v1
kind: Service
metadata:
  name: upload2
spec:
  selector:
    app: upload2
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload2
  template:
    metadata:
      labels:
        app: upload2
    spec:
      containers:
        - image: svenstaro/miniserve:alpine
          name: miniserve
          args:
            - -u
            - -U
            - /mnt/baza
          volumeMounts:
            - name: emptydir-baza
              mountPath: /mnt/baza
          ports:
            - containerPort: 8080
      volumes:
        - name: emptydir-baza
          emptyDir:



---

apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  selector:
    app: canary
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
        - image: svenstaro/miniserve:alpine
          name: miniserve
          args:
            - -u
            - -U
            - /mnt/baza
          volumeMounts:
            - name: emptydir-baza
              mountPath: /mnt/baza
          ports:
            - containerPort: 8080
      volumes:
        - name: emptydir-baza
          emptyDir:
