all:
  vars:
    zmienna_smok: 3
  children:
    mojagrupa:
  hosts:
    docker1:
      ansible_host: 172.17.0.2
      ansible_user: root
    docker2:
      ansible_host: 172.17.0.3
      ansible_user: root
